### ISSUE TITLE
How to register for all users?

### ISSUE THREAD

**Issue by ban-dana** [xandfis/W11ContextMenuDemo#1]
Hello,

the sample here uses PackageManager.AddPackageByUriAsync which regsiters the package per-user.
What's the way to do that machine-wide?

**Comment by ban-dana** [comment]
Thank you, that seems to work. By the way, what's the proper way to get the pkgfamilyname out of the msix?

**Comment by xandfis** [comment]
What's the environment where you need that? Just on-demand from PowerShell or something else?

**Comment by ban-dana** [comment]
My installer's custom action that will run the code above. I found out that IAppxManifestPackageId::GetPackageFamilyName seems to do the trick, is that the right way?

**Comment by DrusTheAxe** [comment]
> By the way, what's the proper way to get the pkgfamilyname out of the msix?

Yes. Use the [PackageReader](https://learn.microsoft.com/windows/win32/api/appxpackaging/nn-appxpackaging-iappxpackagereader) API to crack open a .msix and get a [ManifestReader](https://learn.microsoft.com/windows/win32/api/appxpackaging/nn-appxpackaging-iappxmanifestreader) which have methods to get the package's identity including Package Family Name

Those doc links have more details including links to examples.

**Comment by xandfis** [comment]
I think this has been resolved. If not, please reactivate. Thank you!
